#
# Upgrade to increase the number of item ids to 64K
# By Frey/Gustavo Brigo
#
ALTER TABLE `auction` MODIFY `card0` mediumint(11) NOT NULL default '0',
ALTER TABLE `auction` MODIFY `card1` mediumint(11) NOT NULL default '0',
ALTER TABLE `auction` MODIFY `card2` mediumint(11) NOT NULL default '0',
ALTER TABLE `auction` MODIFY `card3` mediumint(11) NOT NULL default '0',
ALTER TABLE `cart_inventory` MODIFY `card0` mediumint(11) NOT NULL default '0',
ALTER TABLE `cart_inventory` MODIFY `card1` mediumint(11) NOT NULL default '0',
ALTER TABLE `cart_inventory` MODIFY `card2` mediumint(11) NOT NULL default '0',
ALTER TABLE `cart_inventory` MODIFY `card3` mediumint(11) NOT NULL default '0',
ALTER TABLE `guild_storage` MODIFY `card0` mediumint(11) NOT NULL default '0',
ALTER TABLE `guild_storage` MODIFY `card1` mediumint(11) NOT NULL default '0',
ALTER TABLE `guild_storage` MODIFY `card2` mediumint(11) NOT NULL default '0',
ALTER TABLE `guild_storage` MODIFY `card3` mediumint(11) NOT NULL default '0',
ALTER TABLE `inventory` MODIFY `card0` mediumint(11) NOT NULL default '0',
ALTER TABLE `inventory` MODIFY `card1` mediumint(11) NOT NULL default '0',
ALTER TABLE `inventory` MODIFY `card2` mediumint(11) NOT NULL default '0',
ALTER TABLE `inventory` MODIFY `card3` mediumint(11) NOT NULL default '0',
ALTER TABLE `storage` MODIFY `card0` mediumint(11) NOT NULL default '0',
ALTER TABLE `storage` MODIFY `card1` mediumint(11) NOT NULL default '0',
ALTER TABLE `storage` MODIFY `card2` mediumint(11) NOT NULL default '0',
ALTER TABLE `storage` MODIFY `card3` mediumint(11) NOT NULL default '0',
ALTER TABLE `mail` MODIFY `card0` mediumint(11) NOT NULL default '0',
ALTER TABLE `mail` MODIFY `card1` mediumint(11) NOT NULL default '0',
ALTER TABLE `mail` MODIFY `card2` mediumint(11) NOT NULL default '0',
ALTER TABLE `mail` MODIFY `card3` mediumint(11) NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `MVP1id` mediumint(9) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `MVP2id` mediumint(9) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `MVP3id` mediumint(9) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `Drop1id` mediumint(9) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `Drop2id` mediumint(9) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `Drop3id` mediumint(9) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `Drop4id` mediumint(9) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `Drop5id` mediumint(9) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `Drop6id` mediumint(9) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `Drop7id` mediumint(9) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `Drop8id` mediumint(9) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `Drop9id` mediumint(9) unsigned NOT NULL default '0',
ALTER TABLE `mob_db` MODIFY `DropCardid` mediumint(9) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `MVP1id` mediumint(9) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `MVP2id` mediumint(9) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `MVP3id` mediumint(9) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `Drop1id` mediumint(9) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `Drop2id` mediumint(9) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `Drop3id` mediumint(9) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `Drop4id` mediumint(9) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `Drop5id` mediumint(9) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `Drop6id` mediumint(9) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `Drop7id` mediumint(9) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `Drop8id` mediumint(9) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `Drop9id` mediumint(9) unsigned NOT NULL default '0',
ALTER TABLE `mob_db2` MODIFY `DropCardid` mediumint(9) unsigned NOT NULL default '0',